project:
  type: book
  output-dir: docs
profiles:
  - ru
  - en
website:
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - about.qmd 
