project:
  type: book
  output-dir: docs/ru

book:
  title: "Введение в Zig"
  subtitle: "книга на основе проектов"
  author: "Педру Дуарте Фария"
  edition: 1
  date: "today"
  google-analytics: "G-6CHJXK4CEV"
  cover-image: "Cover/cover-artv3.png"
  chapters:
    - index.qmd
    - references.qmd

bibliography: references.bib
execute:
  freeze: auto

website:
  title: "Введение в Zig"

highlight-style: github
format:
  html:
    theme:
      light: cosmo
      dark: darkly
    lang: ru
